export const GET_COMPANIES = 'GET_COMPANIES';
export const COMPANY_ERROR = 'COMPANY_ERROR';

export const GET_OWNERS = 'GET_OWNERS';
export const OWNER_ERROR = 'OWNER_ERROR';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR';

export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_USER_OWNERS = 'GET_USER_OWNERS';
export const GET_USER_COMPANIES = 'GET_USER_COMPANIES';
export const ADD_USER_OWNERS = 'GET_USER_OWNERS';
export const ADD_USER_COMPANIES = 'GET_USER_COMPANIES';
export const USER_ERROR = 'USER_ERROR';
